# Generated by Django 4.1.8 on 2023-04-23 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=16)),
                ('nome', models.CharField(max_length=150)),
                ('idade', models.IntegerField()),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.IntegerField(null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=30)),
                ('lista_de_bens', models.TextField()),
                ('fonte_renda', models.TextField()),
            ],
        ),
    ]
