# Generated by Django 4.2 on 2023-04-24 02:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='movimentacao_financeira',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_consulta',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
