# Generated by Django 4.2 on 2023-04-24 02:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseB', '0002_cliente_movimentacao_financeira_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='movimentacao_financeira',
            field=models.DateTimeField(auto_now_add=True, verbose_name=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultima_consulta',
            field=models.DateTimeField(auto_now_add=True, verbose_name=django.utils.timezone.now),
        ),
    ]
